feat: hw11: add test-coverage-report & CI/CD

diff --git a/.github/workflows/react-2025-08-hw11-les19-jest.yml b/.github/workflows/react-2025-08-hw11-les19-jest.yml
--- a/.github/workflows/react-2025-08-hw11-les19-jest.yml
+++ b/.github/workflows/react-2025-08-hw11-les19-jest.yml
@@ -14,6 +14,7 @@ permissions:
 jobs:
 
   test-report:
+    #find at https://alexanderpono.github.io/ponomarenko-alex-otus/react-2025-08/react-2025-08-hw11-les19-jest/test-report/testResult.html
     runs-on: ubuntu-latest
     defaults:
       run:
@@ -47,10 +48,46 @@ jobs:
         run: |
           if [ ${{ job.status }} == 'failure' ]; then exit 1; fi;
 
-
-  app:
+  test-coverage-report:
+    #find at https://alexanderpono.github.io/ponomarenko-alex-otus/react-2025-08/react-2025-08-hw11-les19-jest/test-coverage-report/lcov-report/
     runs-on: ubuntu-latest
     needs: test-report
+    defaults:
+      run:
+        working-directory: react-2025-08/react-2025-08-hw11-les19-jest
+
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
+        with:
+          node-version: '20'
+
+      # Устанавливаем зависимости
+      - name: Install dependencies
+        run: npm install
+
+      # Запускаем тесты и линтер
+      - name: Run tests
+        run: npm test
+
+      - name: Deploy test-report to GHP /ponomarenko-alex-otus/react-2025-08/react-2025-08-hw11-les19-jest/test-coverage-report 🚀
+        id: Deploy-Project
+        uses: JamesIves/github-pages-deploy-action@4.2.1
+        with:
+          branch: gh-pages # The branch the action should deploy to.
+          folder: react-2025-08/react-2025-08-hw11-les19-jest/coverage  # The folder the action should deploy.
+          target-folder: react-2025-08/react-2025-08-hw11-les19-jest/test-coverage-report
+          clean: true # Automatically remove deleted files from the deploy branch
+
+      # Останавливаем выполнение строго при неудачных тестах
+      # - name: Fail on failed tests
+      #   run: |
+      #     if [ ${{ job.status }} == 'failure' ]; then exit 1; fi;
+
+  app:
+    #find at https://alexanderpono.github.io/ponomarenko-alex-otus/react-2025-08/react-2025-08-hw11-les19-jest/app/
+    runs-on: ubuntu-latest
+    needs: test-coverage-report
     defaults:
       run:
         working-directory: react-2025-08/react-2025-08-hw11-les19-jest
@@ -87,6 +124,7 @@ jobs:
       #     if [ ${{ job.status }} == 'failure' ]; then exit 1; fi;
 
   storybook:
+    #find at https://alexanderpono.github.io/ponomarenko-alex-otus/react-2025-08/react-2025-08-hw11-les19-jest/storybook/?path=/docs/features-editproductform--docs
     runs-on: ubuntu-latest
     needs: app
     defaults:
